=== twinslash/routino/xml/routino-translations.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================
     $Header: /home/amb/routino/xml/RCS/routino-translations.xsd,v 1.3 2010/05/29 13:54:43 amb Exp $

     An XML Schema Definition for the Routino translations XML format

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- The top level Routino translation -->

  <xsd:element name="routino-translations" type="RoutinoTranslationsType"/>

  <xsd:complexType name="RoutinoTranslationsType">
    <xsd:sequence>
      <xsd:element name="language" type="languageType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="languageType">
    <xsd:sequence>
      <xsd:element name="copyright"   type="CopyrightType" minOccurs="0"/>
      <xsd:element name="turn"        type="TurnType"      minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="heading"     type="HeadingType"   minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="highway"     type="HighwayType"   minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="route"       type="RouteType"     minOccurs="0" maxOccurs="2"/>
      <xsd:element name="output-html" type="HTMLType"      minOccurs="0"/>
      <xsd:element name="output-gpx"  type="GPXType"       minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="lang"        type="xsd:string"/>
  </xsd:complexType>

  <!-- The copyright information (of the generated output, not of this file) -->

  <xsd:complexType name="CopyrightType">
    <xsd:sequence>
      <xsd:element name="creator"   type="CopyrightCreatorType" minOccurs="0"/>
      <xsd:element name="source"    type="CopyrightSourceType"  minOccurs="0"/>
      <xsd:element name="license"   type="CopyrightLicenseType" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="CopyrightCreatorType">
    <xsd:attribute name="string"  type="xsd:string"/>
    <xsd:attribute name="text"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="CopyrightSourceType">
    <xsd:attribute name="string"  type="xsd:string"/>
    <xsd:attribute name="text"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="CopyrightLicenseType">
    <xsd:attribute name="string"  type="xsd:string"/>
    <xsd:attribute name="text"    type="xsd:string"/>
  </xsd:complexType>

  <!-- The turn, heading, highway and route strings -->

  <xsd:complexType name="TurnType">
    <xsd:attribute name="direction" type="xsd:string"/>
    <xsd:attribute name="string"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HeadingType">
    <xsd:attribute name="direction" type="xsd:string"/>
    <xsd:attribute name="string"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HighwayType">
    <xsd:attribute name="type"      type="xsd:string"/>
    <xsd:attribute name="string"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="RouteType">
    <xsd:attribute name="type"      type="xsd:string"/>
    <xsd:attribute name="string"    type="xsd:string"/>
  </xsd:complexType>

  <!-- The HTML output strings -->

  <xsd:complexType name="HTMLType">
    <xsd:sequence>
      <xsd:element name="waypoint" type="HTMLWaypointType" maxOccurs="2"/>
      <xsd:element name="title"    type="HTMLTitleType"/>
      <xsd:element name="start"    type="HTMLStartType"/>
      <xsd:element name="node"     type="HTMLNodeType"/>
      <xsd:element name="segment"  type="HTMLSegmentType"/>
      <xsd:element name="stop"     type="HTMLStopType"/>
      <xsd:element name="total"    type="HTMLTotalType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="HTMLWaypointType">
    <xsd:attribute name="type"   type="xsd:string"/>
    <xsd:attribute name="string" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLTitleType">
    <xsd:attribute name="text"  type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLStartType">
    <xsd:attribute name="string" type="xsd:string"/>
    <xsd:attribute name="text"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLNodeType">
    <xsd:attribute name="string" type="xsd:string"/>
    <xsd:attribute name="text"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLSegmentType">
    <xsd:attribute name="string" type="xsd:string"/>
    <xsd:attribute name="text"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLStopType">
    <xsd:attribute name="string" type="xsd:string"/>
    <xsd:attribute name="text"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="HTMLTotalType">
    <xsd:attribute name="string" type="xsd:string"/>
    <xsd:attribute name="text"   type="xsd:string"/>
  </xsd:complexType>

  <!-- The GPX output strings -->

  <xsd:complexType name="GPXType">
    <xsd:sequence>
      <xsd:element name="waypoint" type="GPXWaypointType" maxOccurs="4"/>
      <xsd:element name="desc"     type="GPXDescType"/>
      <xsd:element name="name"     type="GPXNameType"/>
      <xsd:element name="step"     type="GPXStepType"/>
      <xsd:element name="final"    type="GPXFinalType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="GPXWaypointType">
    <xsd:attribute name="type"   type="xsd:string"/>
    <xsd:attribute name="string" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="GPXDescType">
    <xsd:attribute name="text"  type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="GPXNameType">
    <xsd:attribute name="text"  type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="GPXStepType">
    <xsd:attribute name="text"  type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="GPXFinalType">
    <xsd:attribute name="text"  type="xsd:string"/>
  </xsd:complexType>

</xsd:schema>

=== twinslash/routino/xml/routino-translations.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================
     $Header: /home/amb/routino/xml/RCS/routino-translations.xml,v 1.5 2010/07/03 11:27:37 amb Exp $

     An XML format file containing Routino output translations.

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<routino-translations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:noNamespaceSchemaLocation="http://www.routino.org/xml/routino-translations.xsd">

  <language lang="en">

    <!-- Copyright of the data being routed, not of this file  -->
    <copyright>
      <creator string="Creator" text="Routino - http://www.routino.org/" />
      <source  string="Source"  text="Based on OpenStreetMap data from http://www.openstreetmap.org/" />
      <license string="License" text="http://creativecommons.org/licenses/by-sa/2.0/" />
    </copyright>

    <!-- Turn directions, 0 = ahead, -2 = left, +/-4 = behind, +2 = right -->
    <turn direction="-4" string="Very sharp left" />
    <turn direction="-3" string="Sharp left" />
    <turn direction="-2" string="Left" />
    <turn direction="-1" string="Slight left" />
    <turn direction="0"  string="Straight on" />
    <turn direction="1"  string="Slight right" />
    <turn direction="2"  string="Right" />
    <turn direction="3"  string="Sharp right" />
    <turn direction="4"  string="Very sharp right" />

    <!-- Heading directions, 0 = North, -2 = West, +/-4 = South, +2 = East -->
    <heading direction="-4" string="South" />
    <heading direction="-3" string="South-West" />
    <heading direction="-2" string="West" />
    <heading direction="-1" string="North-West" />
    <heading direction="0"  string="North" />
    <heading direction="1"  string="North-East" />
    <heading direction="2"  string="East" />
    <heading direction="3"  string="South-East" />
    <heading direction="4"  string="South" />

    <!-- Highway names -->
    <highway type="motorway"     string="motorway" />
    <highway type="trunk"        string="trunk road" />
    <highway type="primary"      string="primary road" />
    <highway type="secondary"    string="secondary road" />
    <highway type="tertiary"     string="tertiary road" />
    <highway type="unclassified" string="unclassified road" />
    <highway type="residential"  string="residential road" />
    <highway type="service"      string="service road" />
    <highway type="track"        string="track" />
    <highway type="cycleway"     string="cycleway" />
    <highway type="path"         string="path" />
    <highway type="steps"        string="steps" />

    <!-- The type of route -->
    <route type="shortest" string="Shortest" /> <!-- For the description and route name -->
    <route type="quickest" string="Quickest" /> <!-- For the description and route name -->

    <!-- HTML output -->
    <output-html>
      <waypoint type="waypoint"  string="Waypoint" /> <!-- For the chosen waypoints -->
      <waypoint type="junction"  string="Junction" /> <!-- For the interesting junctions -->

      <title text="%s Route" /> <!-- %s = [shortest|quickest] -->

      <start   string="Start"  text="At %s, head %s" />           <!-- 1st %s = [waypoint|junction], 2nd %s = [heading] -->
      <node    string="At"     text="%s, go %s heading %s" />     <!-- 1st %s = [waypoint|junction], 2nd %s = [turn], 3rd %s = [heading] -->
      <segment string="Follow" text="%s for %.3f km, %.1f min" /> <!-- 1st %s = street name -->
      <stop    string="Stop"   text="At %s" />                    <!-- 1st %s = [waypoint|junction] -->
      <total   string="Total"  text="%.1f km, %.0f minutes" />
    </output-html>

    <!-- GPX output -->
    <output-gpx>
      <waypoint type="start"  string="START" /> <!-- For the first route waypoint -->
      <waypoint type="inter"  string="INTER" /> <!-- For the intermediate route waypoints -->
      <waypoint type="trip"   string="TRIP"  /> <!-- For the other route points -->
      <waypoint type="finish" string="FINISH"/> <!-- For the last route waypoint -->

      <desc  text="%s route between 'start' and 'finish' waypoints" /> <!-- %s = [shortest|quickest] -->
      <name  text="%s route" />                                        <!-- %s = [shortest|quickest] -->
      <step  text="%s on '%s' for %.3f km, %.1f min" />                <!-- 1st %s = [turn], 2nd %s = street name -->
      <final text="Total Journey %.1f km, %.0f minutes" />
    </output-gpx>

  </language>

  <language lang="de">

    <!-- Copyright of the data being routed, not of this file  -->
    <copyright>
      <creator string="Creator" text="Routino - http://www.routino.org/" />
      <source  string="Source"  text="Basierend auf OpenStreetMap-Daten, erhältlich via http://www.openstreetmap.org/" />
      <license string="License" text="http://creativecommons.org/licenses/by-sa/2.0/" />
    </copyright>

    <!-- Turn directions, 0 = ahead, -2 = left, +/-4 = behind, +2 = right -->
    <turn direction="-4" string="Spitzkehre nach links" />
    <turn direction="-3" string="Scharf links" />
    <turn direction="-2" string="Links" />
    <turn direction="-1" string="Halb links" />
    <turn direction="0"  string="Geradeaus" />
    <turn direction="1"  string="Halb rechts" />
    <turn direction="2"  string="Rechts" />
    <turn direction="3"  string="Scharf rechts" />
    <turn direction="4"  string="Spitzkehre nach rechts" />

    <!-- Heading directions, 0 = North, -2 = West, +/-4 = South, +2 = East -->
    <heading direction="-4" string="Süd" />
    <heading direction="-3" string="Süd-West" />
    <heading direction="-2" string="West" />
    <heading direction="-1" string="Nord-West" />
    <heading direction="0"  string="Nord" />
    <heading direction="1"  string="Nord-Ost" />
    <heading direction="2"  string="Ost" />
    <heading direction="3"  string="Süd-Ost" />
    <heading direction="4"  string="Süd" />

    <!-- Highway names -->
    <highway type="motorway"     string="Autobahn" />
    <highway type="trunk"        string="Schnellstraße" />
    <highway type="primary"      string="Bundesstraße" />
    <highway type="secondary"    string="Landstraße" />
    <highway type="tertiary"     string="Kreisstraße" />
    <highway type="unclassified" string="Nebenstraße" />
    <highway type="residential"  string="Wohngebietsstraße" />
    <highway type="service"      string="Erschließungsweg" />
    <highway type="track"        string="Wirtschaftsweg" />
    <highway type="cycleway"     string="Radweg" />
    <highway type="path"         string="Weg" />
    <highway type="steps"        string="Treppe" />

    <!-- The type of route -->
    <route type="shortest" string="Kürzeste" />   <!-- For the description and route name -->
    <route type="quickest" string="Schnellste" /> <!-- For the description and route name -->

    <!-- HTML output -->
    <output-html>
      <waypoint type="waypoint"  string="Wegpunkt" /> <!-- For the chosen waypoints -->
      <waypoint type="junction"  string="Anschlussstelle" /> <!-- For the interesting junctions -->

      <title text="%s Route" /> <!-- %s = [shortest|quickest] -->

      <start   string="Start"  text="Bei %s halten Sie sich Richtung %s" />          <!-- 1st %s = [waypoint|junction], 2nd %s = [heading] -->
      <node    string="Bei"    text="Bei %s wenden Sie sich nach %s Richtung %s" />  <!-- 1st %s = [waypoint|junction], 2nd %s = [turn], 3rd %s = [heading] -->
      <segment string="Folgen" text="Folgen Sie der %s für %.3f km bzw. %.1f min" /> <!-- 1st %s = street name -->
      <stop    string="Stop"   text="Sie sind bei %s angekommen" />                  <!-- 1st %s = [waypoint|junction] -->
      <total   string="Gesamt" text="%.1f km, %.0f minuten" />
    </output-html>

    <!-- GPX output -->
    <output-gpx>
      <waypoint type="start"  string="START" /> <!-- For the first route waypoint -->
      <waypoint type="inter"  string="INTER" /> <!-- For the intermediate route waypoints -->
      <waypoint type="trip"   string="TRIP"  /> <!-- For the other route points -->
      <waypoint type="finish" string="FINISH"/> <!-- For the last route waypoint -->

      <desc  text="%s Strecke zwischen 'Start' und 'Ziel'" />           <!-- %s = [shortest|quickest] -->
      <name  text="%s Strecke" />                                       <!-- %s = [shortest|quickest] -->
      <step  text="%s auf '%s' für %.3f km, %.1f min" />                <!-- 1st %s = [turn], 2nd %s = street name -->
      <final text="Gesamtstrecke %.1f km, %.0f minuten" />
    </output-gpx>

  </language>

</routino-translations>
