=== twinslash/routino/xml/routino-tagging.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================
     $Header: /home/amb/routino/xml/RCS/routino-tagging.xsd,v 1.1 2010/05/18 18:35:01 amb Exp $

     An XML Schema Definition for the Routino tagging rules XML format

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- The top level Routino tagging rules -->

  <xsd:element name="routino-tagging" type="RoutinoTaggingType"/>

  <xsd:complexType name="RoutinoTaggingType">
    <xsd:sequence>
      <xsd:element name="node"        type="NodeType"/>
      <xsd:element name="way"         type="WayType"/>
      <xsd:element name="relation"    type="RelationType"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- The second level node, way and relation tagging rules -->

  <xsd:complexType name="NodeType">
  </xsd:complexType>

  <xsd:complexType name="WayType">
    <xsd:sequence>
      <xsd:element name="if" type="IfType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="RelationType">
  </xsd:complexType>

  <!-- The if tag and its contents -->

  <xsd:complexType name="IfType">
    <xsd:sequence>
      <xsd:element name="set"      type="SetType"     minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="output"   type="OutputType"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="k" type="xsd:string"/>
    <xsd:attribute name="v" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="SetType">
    <xsd:attribute name="k" type="xsd:string"/>
    <xsd:attribute name="v" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="OutputType">
    <xsd:attribute name="k" type="xsd:string"/>
    <xsd:attribute name="v" type="xsd:string"/>
  </xsd:complexType>

</xsd:schema>

=== twinslash/routino/xml/routino-tagging.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- ============================================================
     $Header: /home/amb/routino/xml/RCS/routino-tagging.xml,v 1.2 2010/06/26 19:26:47 amb Exp $

     An XML format file containing Routino tagging rules

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<routino-tagging xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="http://www.routino.org/xml/routino-tagging.xsd">

  <!-- Node rules are not currently used -->

  <node>
  </node>

  <!-- Way rules -->

  <way>

    <!-- Highway types (includes default access and default properties) -->

    <if k="highway" v="motorway_link">
      <set v="motorway"/>
    </if>

    <if k="highway" v="motorway">
      <output k="highway"/>

      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
      <output k="multilane"  v="yes"/>
      <output k="oneway"     v="yes"/>
    </if>

    <if k="highway" v="trunk_link">
      <set v="trunk"/>
    </if>

    <if k="highway" v="trunk">
      <output k="highway"/>

      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="primary_link">
      <set v="primary"/>
    </if>

    <if k="highway" v="primary">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="no"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="secondary_link">
      <set v="secondary"/>
    </if>

    <if k="highway" v="secondary">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="tertiary">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="minor">
      <set k="highway" v="unclassified"/>
    </if>

    <if k="highway" v="road">
      <set k="highway" v="unclassified"/>
    </if>

    <if k="highway" v="unclassified">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="living_street">
      <set k="highway" v="residential"/>
    </if>

    <if k="highway" v="residential">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="services">
      <set k="highway" v="service"/>
    </if>

    <if k="highway" v="service">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
      <output k="goods"      v="yes"/>
      <output k="hgv"        v="yes"/>
      <output k="psv"        v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="byway">
      <set k="highway" v="track"/>
    </if>

    <if k="highway" v="unsurfaced">
      <set k="highway" v="track"/>
    </if>

    <if k="highway" v="unpaved">
      <set k="highway" v="track"/>
    </if>

    <if k="highway" v="track">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="bicycle"    v="yes"/>
    </if>

    <if k="tracktype" v="grade1">
      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="cycleway">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="footway">
      <set k="highway" v="path"/>
    </if>

    <if k="highway" v="bridleway">
      <set k="highway" v="path"/>

      <output k="horse"      v="yes"/>
      <output k="bicycle"    v="yes"/>
    </if>

    <if k="highway" v="pedestrian">
      <set k="highway" v="path"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="walkway">
      <set k="highway"  v="path"/>

      <output k="paved"      v="yes"/>
    </if>

    <if k="highway" v="path">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
      <output k="wheelchair" v="yes"/>
    </if>

    <if k="highway" v="steps">
      <output k="highway"/>

      <output k="foot"       v="yes"/>
    </if>

    <if k="junction" v="roundabout">
      <output k="junction" v="roundabout"/>
      <output k="oneway"   v="yes"/>
    </if>

    <!-- Normalisation of access tags -->

    <if v="designated" ><set v="yes"/></if>
    <if v="permissive" ><set v="yes"/></if>
    <if v="destination"><set v="yes"/></if>

    <if v="private"><set v="no"/></if>

    <!-- Generic access permissions for all transport types (to override defaults) -->

    <if k="access">
      <set k="noaccess" v="yes"/>
    </if>

    <if k="access" v="true">
      <set k="noaccess" v="no"/>
    </if>

    <if k="access" v="yes">
      <set k="noaccess" v="no"/>
    </if>

    <if k="noaccess" v="yes">
      <output k="foot"       v="no"/>
      <output k="horse"      v="no"/>
      <output k="wheelchair" v="no"/>
      <output k="bicycle"    v="no"/>
      <output k="moped"      v="no"/>
      <output k="motorbike"  v="no"/>
      <output k="motorcar"   v="no"/>
      <output k="goods"      v="no"/>
      <output k="hgv"        v="no"/>
      <output k="psv"        v="no"/>
    </if>

    <!-- Generic access permissions for classes of transport types -->

    <if k="motor_vehicle">
      <output k="moped"/>
      <output k="motorbike"/>
      <output k="motorcar"/>
      <output k="goods"/>
      <output k="hgv"/>
      <output k="psv"/>
    </if>

    <if k="vehicle">
      <output k="bicycle"/>
      <output k="moped"/>
      <output k="motorbike"/>
      <output k="motorcar"/>
      <output k="goods"/>
      <output k="hgv"/>
      <output k="psv"/>
    </if>

    <!-- Other access permissions (UK) -->

    <if k="designation" v="restricted_byway">
      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
    </if>

    <if k="designation" v="byway">
      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
      <output k="moped"      v="yes"/>
      <output k="motorbike"  v="yes"/>
      <output k="motorcar"   v="yes"/>
    </if>

    <if k="designation" v="public_bridleway">
      <set v="bridleway"/>
    </if>

    <if k="designation" v="bridleway">
      <output k="foot"       v="yes"/>
      <output k="horse"      v="yes"/>
      <output k="wheelchair" v="yes"/>
      <output k="bicycle"    v="yes"/>
    </if>

    <if k="designation" v="public_footpath">
      <set v="footpath"/>
    </if>

    <if k="designation" v="footpath">
      <output k="foot"       v="yes"/>
      <output k="wheelchair" v="yes"/>
    </if>

    <!-- Specific access rules (to override the generic ones) -->

    <if k="foot"      ><output/></if>
    <if k="horse"     ><output/></if>
    <if k="wheelchair"><output/></if>
    <if k="bicycle"   ><output/></if>
    <if k="moped"     ><output/></if>
    <if k="motorbike" ><output/></if>
    <if k="motorcar"  ><output/></if>
