=== twinslash/routino/xml/routino-profiles.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================
     $Header$

     An XML Schema Definition for the Routino profile XML format

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- The top level Routino profiles -->

  <xsd:element name="routino-profiles" type="RoutinoProfilesType"/>

  <xsd:complexType name="RoutinoProfilesType">
    <xsd:sequence>
      <xsd:element name="profile" type="profileType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="profileType">
    <xsd:sequence>
      <xsd:element name="speeds"       type="speedsType"      />
      <xsd:element name="preferences"  type="preferencesType" />
      <xsd:element name="properties"   type="propertiesType"  />
      <xsd:element name="restrictions" type="restrictionsType"/>
    </xsd:sequence>
    <xsd:attribute name="name"         type="xsd:string"/>
    <xsd:attribute name="transport"    type="xsd:string"/>
  </xsd:complexType>

  <!-- The second level preferences, speed, properties and restrictions -->

  <xsd:complexType name="speedsType">
    <xsd:sequence>
      <xsd:element name="speed" type="speedType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="preferencesType">
    <xsd:sequence>
      <xsd:element name="preference" type="preferenceType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="propertiesType">
    <xsd:sequence>
      <xsd:element name="property" type="propertyType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="restrictionsType">
    <xsd:sequence>
      <xsd:element name="oneway" type="onewayType"/>
      <xsd:element name="weight" type="weightType"/>
      <xsd:element name="height" type="heightType"/>
      <xsd:element name="width"  type="widthType"/>
      <xsd:element name="length" type="lengthType"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- The lowest level elements containing the real information -->

  <xsd:complexType name="speedType">
    <xsd:attribute name="highway" type="xsd:string"/>
    <xsd:attribute name="kph"     type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="preferenceType">
    <xsd:attribute name="highway" type="xsd:string"/>
    <xsd:attribute name="percent" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="propertyType">
    <xsd:attribute name="type"    type="xsd:string"/>
    <xsd:attribute name="percent" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="onewayType">
    <xsd:attribute name="obey"    type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="weightType">
    <xsd:attribute name="limit"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="heightType">
    <xsd:attribute name="limit"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="widthType">
    <xsd:attribute name="limit"   type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="lengthType">
    <xsd:attribute name="limit"   type="xsd:string"/>
  </xsd:complexType>

</xsd:schema>

=== twinslash/routino/xml/routino-profiles.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- ============================================================
     $Header: /home/amb/routino/xml/RCS/routino-profiles.xml,v 1.2 2010/06/26 19:26:47 amb Exp $

     An XML format file containing Routino routing profiles

     Part of the Routino routing software.
     ============================================================
     This file Copyright 2010 Andrew M. Bishop

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU Affero General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     ============================================================ -->

<routino-profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="http://www.routino.org/xml/routino-profiles.xsd">

  <profile name="foot" transport="foot">
    <speeds>
      <speed highway="motorway"      kph="0" />
      <speed highway="trunk"         kph="4" />
      <speed highway="primary"       kph="4" />
      <speed highway="secondary"     kph="4" />
      <speed highway="tertiary"      kph="4" />
      <speed highway="unclassified"  kph="4" />
      <speed highway="residential"   kph="4" />
      <speed highway="service"       kph="4" />
      <speed highway="track"         kph="4" />
      <speed highway="cycleway"      kph="4" />
      <speed highway="path"          kph="4" />
      <speed highway="steps"         kph="4" />
    </speeds>
    <preferences>
      <preference highway="motorway"      percent="0" />
      <preference highway="trunk"         percent="40" />
      <preference highway="primary"       percent="50" />
      <preference highway="secondary"     percent="60" />
      <preference highway="tertiary"      percent="70" />
      <preference highway="unclassified"  percent="80" />
      <preference highway="residential"   percent="90" />
      <preference highway="service"       percent="90" />
      <preference highway="track"         percent="95" />
      <preference highway="cycleway"      percent="95" />
      <preference highway="path"          percent="100" />
      <preference highway="steps"         percent="80" />
    </preferences>
    <properties>
      <property type="paved"      percent="50" />
      <property type="multilane"  percent="25" />
      <property type="bridge"     percent="50" />
      <property type="tunnel"     percent="50" />
    </properties>
    <restrictions>
      <oneway obey="0" /> 
      <weight limit="0.0" />
      <height limit="0.0" />
      <width  limit="0.0" />
      <length limit="0.0" />
    </restrictions>
  </profile>

  <profile name="horse" transport="horse">
    <speeds>
      <speed highway="motorway"      kph="0" />
      <speed highway="trunk"         kph="8" />
      <speed highway="primary"       kph="8" />
      <speed highway="secondary"     kph="8" />
      <speed highway="tertiary"      kph="8" />
      <speed highway="unclassified"  kph="8" />
      <speed highway="residential"   kph="8" />
      <speed highway="service"       kph="8" />
      <speed highway="track"         kph="8" />
      <speed highway="cycleway"      kph="8" />
      <speed highway="path"          kph="8" />
      <speed highway="steps"         kph="0" />
    </speeds>
    <preferences>
      <preference highway="motorway"      percent="0" />
      <preference highway="trunk"         percent="25" />
      <preference highway="primary"       percent="50" />
      <preference highway="secondary"     percent="50" />
      <preference highway="tertiary"      percent="75" />
      <preference highway="unclassified"  percent="75" />
      <preference highway="residential"   percent="75" />
      <preference highway="service"       percent="75" />
      <preference highway="track"         percent="100" />
      <preference highway="cycleway"      percent="90" />
      <preference highway="path"          percent="100" />
      <preference highway="steps"         percent="0" />
    </preferences>
    <properties>
      <property type="paved"      percent="20" />
      <property type="multilane"  percent="25" />
      <property type="bridge"     percent="50" />
      <property type="tunnel"     percent="50" />
    </properties>
    <restrictions>
      <oneway obey="1" /> 
      <weight limit="0.0" />
      <height limit="0.0" />
      <width  limit="0.0" />
      <length limit="0.0" />
    </restrictions>
  </profile>

  <profile name="wheelchair" transport="wheelchair">
    <speeds>
      <speed highway="motorway"      kph="0" />
      <speed highway="trunk"         kph="4" />
      <speed highway="primary"       kph="4" />
      <speed highway="secondary"     kph="4" />
      <speed highway="tertiary"      kph="4" />
      <speed highway="unclassified"  kph="4" />
      <speed highway="residential"   kph="4" />
      <speed highway="service"       kph="4" />
      <speed highway="track"         kph="4" />
      <speed highway="cycleway"      kph="4" />
      <speed highway="path"          kph="4" />
      <speed highway="steps"         kph="4" />
    </speeds>
    <preferences>
      <preference highway="motorway"      percent="0" />
      <preference highway="trunk"         percent="40" />
      <preference highway="primary"       percent="50" />
      <preference highway="secondary"     percent="60" />
      <preference highway="tertiary"      percent="70" />
      <preference highway="unclassified"  percent="80" />
      <preference highway="residential"   percent="90" />
      <preference highway="service"       percent="90" />
      <preference highway="track"         percent="95" />
      <preference highway="cycleway"      percent="95" />
      <preference highway="path"          percent="100" />
      <preference highway="steps"         percent="0" />
    </preferences>
    <properties>
      <property type="paved"      percent="90" />
      <property type="multilane"  percent="25" />
      <property type="bridge"     percent="50" />
      <property type="tunnel"     percent="50" />
    </properties>
    <restrictions>
      <oneway obey="0" /> 
      <weight limit="0.0" />
      <height limit="0.0" />
      <width  limit="0.0" />
      <length limit="0.0" />
    </restrictions>
  </profile>

  <profile name="bicycle" transport="bicycle">
    <speeds>
      <speed highway="motorway"      kph="0" />
      <speed highway="trunk"         kph="20" />
      <speed highway="primary"       kph="20" />
      <speed highway="secondary"     kph="20" />
      <speed highway="tertiary"      kph="20" />
      <speed highway="unclassified"  kph="20" />
      <speed highway="residential"   kph="20" />
      <speed highway="service"       kph="20" />
      <speed highway="track"         kph="20" />
      <speed highway="cycleway"      kph="20" />
      <speed highway="path"          kph="20" />
      <speed highway="steps"         kph="0" />
    </speeds>
    <preferences>
      <preference highway="motorway"      percent="0" />
      <preference highway="trunk"         percent="30" />
      <preference highway="primary"       percent="70" />
      <preference highway="secondary"     percent="80" />
      <preference highway="tertiary"      percent="90" />
      <preference highway="unclassified"  percent="90" />
      <preference highway="residential"   percent="90" />
      <preference highway="service"       percent="90" />
      <preference highway="track"         percent="90" />
      <preference highway="cycleway"      percent="100" />
      <preference highway="path"          percent="90" />
      <preference highway="steps"         percent="0" />
    </preferences>
    <properties>
      <property type="paved"      percent="50" />
      <property type="multilane"  percent="25" />
      <property type="bridge"     percent="50" />
      <property type="tunnel"     percent="50" />
    </properties>
    <restrictions>
      <oneway obey="1" /> 
      <weight limit="0.0" />
      <height limit="0.0" />
      <width  limit="0.0" />
      <length limit="0.0" />
    </restrictions>
  </profile>

  <profile name="moped" transport="moped">
    <speeds>
      <speed highway="motorway"      kph="48" />
      <speed highway="trunk"         kph="48" />
      <speed highway="primary"       kph="48" />
      <speed highway="secondary"     kph="48" />
      <speed highway="tertiary"      kph="48" />
      <speed highway="unclassified"  kph="48" />
      <speed highway="residential"   kph="48" />
      <speed highway="service"       kph="32" />
      <speed highway="track"         kph="16" />
      <speed highway="cycleway"      kph="0" />
      <speed highway="path"          kph="0" />
      <speed highway="steps"         kph="0" />
    </speeds>
    <preferences>
      <preference highway="motorway"      percent="0" />
      <preference highway="trunk"         percent="90" />
      <preference highway="primary"       percent="100" />
      <preference highway="secondary"     percent="90" />
      <preference highway="tertiary"      percent="80" />
      <preference highway="unclassified"  percent="70" />
      <preference highway="residential"   percent="60" />
      <preference highway="service"       percent="80" />
      <preference highway="track"         percent="0" />
      <preference highway="cycleway"      percent="0" />
      <preference highway="path"          percent="0" />
      <preference highway="steps"         percent="0" />
    </preferences>
    <properties>
      <property type="paved"      percent="100" />
      <property type="multilane"  percent="25" />
      <property type="bridge"     percent="50" />
      <property type="tunnel"     percent="50" />
    </properties>
    <restrictions>
      <oneway obey="1" /> 
      <weight limit="0.0" />
      <height limit="0.0" />
      <width  limit="0.0" />
      <length limit="0.0" />
    </restrictions>
